### ISSUE TITLE
Pressure and Humidity endpoints are reversed

### ISSUE THREAD

**Issue by florianluediger** [dtext/bme280ws#1]
When calling the endpoint to get the pressure, the humidity is returned. When querying for the humidity, the pressure is returned.

`Bme280::read_sensor` returns temperature, pressure, humidity in this order
(https://github.com/dtext/bme280ws/blob/master/app/weather.py#L15)

The `/humidity` endpoint returns the second return value
(https://github.com/dtext/bme280ws/blob/master/app/main.py#L25)

The `/pressure` endpoint returns the third return value
(https://github.com/dtext/bme280ws/blob/master/app/main.py#L30)

**Comment by dtext** [comment]
Thanks, missed that one!
